/**
 * Phase 2: Puzzle Generator Tests (TDD - Red)
 *
 * Tests for puzzle generation and manipulation logic
 */

import {
  createSolvedState,
  generatePuzzle,
  getValidMoves,
  applyMove,
} from '@/lib/puzzle/generator'
import { PuzzleState, Position } from '@/lib/puzzle/types'

describe('Puzzle Generator', () => {
  describe('createSolvedState', () => {
    it('should create a 4x4 solved puzzle state', () => {
      const state = createSolvedState(4)

      expect(state.size).toBe(4)
      expect(state.tiles).toHaveLength(16)
      expect(state.moves).toBe(0)
      expect(state.isComplete).toBe(true)
      expect(state.emptyTileId).toBe(15)
    })

    it('should create a 5x5 solved puzzle state', () => {
      const state = createSolvedState(5)

      expect(state.size).toBe(5)
      expect(state.tiles).toHaveLength(25)
      expect(state.emptyTileId).toBe(24)
    })

    it('should have tiles in correct positions', () => {
      const state = createSolvedState(4)

      state.tiles.forEach((tile, index) => {
        expect(tile.id).toBe(index)
        expect(tile.position.x).toBe(index % 4)
        expect(tile.position.y).toBe(Math.floor(index / 4))
      })
    })

    it('should mark the last tile as empty', () => {
      const state = createSolvedState(4)
      const lastTile = state.tiles[15]

      expect(lastTile.isEmpty).toBe(true)
      expect(lastTile.id).toBe(15)
    })
  })

  describe('generatePuzzle', () => {
    it('should generate a shuffled puzzle', () => {
      const puzzle = generatePuzzle(4, 20)

      expect(puzzle.size).toBe(4)
      expect(puzzle.tiles).toHaveLength(16)
      expect(puzzle.moves).toBe(0) // Moves counter should be reset
      expect(puzzle.isComplete).toBe(false) // Should not be complete after shuffle
    })

    it('should maintain exactly one empty tile', () => {
      const puzzle = generatePuzzle(4, 20)

      const emptyTiles = puzzle.tiles.filter(t => t.isEmpty)
      expect(emptyTiles).toHaveLength(1)
    })

    it('should shuffle with specified number of moves', () => {
      const puzzle1 = generatePuzzle(4, 5)
      const puzzle2 = generatePuzzle(4, 100)

      // More shuffles should result in different states
      expect(puzzle1).not.toEqual(puzzle2)
    })

    it('should generate solvable puzzles', () => {
      // All puzzles generated by valid moves should be solvable
      const puzzle = generatePuzzle(4, 50)

      // Basic check: puzzle is not in solved state
      expect(puzzle.isComplete).toBe(false)

      // All tiles should have valid positions
      puzzle.tiles.forEach(tile => {
        expect(tile.position.x).toBeGreaterThanOrEqual(0)
        expect(tile.position.x).toBeLessThan(4)
        expect(tile.position.y).toBeGreaterThanOrEqual(0)
        expect(tile.position.y).toBeLessThan(4)
      })
    })
  })

  describe('getValidMoves', () => {
    it('should return valid moves for empty tile in corner', () => {
      // Create a state with empty tile in top-left corner (0,0)
      const state: PuzzleState = {
        size: 4,
        tiles: [],
        emptyTileId: 0,
        moves: 0,
        isComplete: false,
        startTime: null,
        endTime: null,
      }

      // Create tiles with empty at position (0,0)
      for (let i = 0; i < 16; i++) {
        state.tiles.push({
          id: i,
          position: { x: i % 4, y: Math.floor(i / 4) },
          isEmpty: i === 0,
        })
      }

      const validMoves = getValidMoves(state)

      // From top-left, can move right (1) or down (4)
      expect(validMoves).toHaveLength(2)
      expect(validMoves.map(m => m.tileId).sort()).toEqual([1, 4])
    })

    it('should return valid moves for empty tile in center', () => {
      // Create a 4x4 state with empty tile at (1,1) = index 5
      const state: PuzzleState = {
        size: 4,
        tiles: [],
        emptyTileId: 5,
        moves: 0,
        isComplete: false,
        startTime: null,
        endTime: null,
      }

      // Swap tiles 5 and 0 to put empty at position 5
      for (let i = 0; i < 16; i++) {
        let pos
        if (i === 5) {
          pos = { x: 1, y: 1 }
        } else {
          pos = { x: i % 4, y: Math.floor(i / 4) }
        }

        state.tiles.push({
          id: i,
          position: pos,
          isEmpty: i === 5,
        })
      }

      const validMoves = getValidMoves(state)

      // From (1,1), can move in all 4 directions
      expect(validMoves).toHaveLength(4)
    })

    it('should return valid moves for empty tile at edge', () => {
      // Empty tile at top edge (1,0) = index 1
      const state: PuzzleState = {
        size: 4,
        tiles: [],
        emptyTileId: 1,
        moves: 0,
        isComplete: false,
        startTime: null,
        endTime: null,
      }

      for (let i = 0; i < 16; i++) {
        state.tiles.push({
          id: i,
          position: { x: i % 4, y: Math.floor(i / 4) },
          isEmpty: i === 1,
        })
      }

      const validMoves = getValidMoves(state)

      // From top edge (1,0), can move left, right, or down = 3 moves
      expect(validMoves).toHaveLength(3)
    })
  })

  describe('applyMove', () => {
    it('should swap tile with empty tile', () => {
      const state = createSolvedState(4)

      // In solved state, empty is at (3,3) = tile 15
      // Tile at (2,3) = tile 14 can move to empty position
      const validMoves = getValidMoves(state)
      const move = validMoves[0]

      const newState = applyMove(state, move)

      // Move counter should increment
      expect(newState.moves).toBe(1)

      // Tiles should have swapped positions
      const movedTile = newState.tiles.find(t => t.id === move.tileId)!
      const emptyTile = newState.tiles.find(t => t.isEmpty)!

      expect(movedTile.position).toEqual(move.to)
      expect(emptyTile.position).toEqual(move.from)
    })

    it('should not modify original state', () => {
      const state = createSolvedState(4)
      const originalMoves = state.moves

      const validMoves = getValidMoves(state)
      applyMove(state, validMoves[0])

      // Original state should not change
      expect(state.moves).toBe(originalMoves)
    })

    it('should correctly track completion status', () => {
      const state = createSolvedState(4)

      // Apply a move - should no longer be complete
      const validMoves = getValidMoves(state)
      const newState = applyMove(state, validMoves[0])

      expect(newState.isComplete).toBe(false)
    })
  })
})
